function getSampleHeadlines()
{
  d= [];
  
  d.push("    Price said at a New Hampshire event");
  d.push("    as his partner");
  d.push("which oversees some of America   s most elite forces");
  d.push("Greg Gutfeld: The guilty sins of WikiLeaks and our wicked approval");
  d.push("Hooters waitresses in Asia told to wear more  clothes");
  d.push("The Gun-Control Farce");
  d.push("New York pols    race to be the biggest LGBT  panderers");
  d.push("Muhammad Ali   s final photo shoot captured a spark that still lingered");
  d.push("one critically");
  d.push("Hong Kong was supposed to liberalize China. How did the opposite happen?"); 
  d.push("The Russia probe is too important to be muddled by  politics");
  d.push("Illustrators get us up close with alien planets");
  d.push("White Nationalist PAC Plans New Wave Of Pro-Trump Robocalls");
  d.push("Donald Trump:    I humbly and gratefully accept your nomination for president of the United States   ");
  d.push("Iceland Airwaves festival day four     Bj  rk   s the star in her home country");
  d.push("everyone agrees that to finish second to Simone Biles is the same as finishing first.    If you get silver");
  d.push("A literary guide to hating Barack Obama");
  d.push("identified by sources as Alyssa Elsman");
  d.push("10 Things You Need to Know Before Seeing    Doctor Strange    - The New York Times");
  d.push("unsettling visual. The camera rests on a row of carefully arranged empty chairs");
  d.push("Republicans Leave Town Without Punishing Democrats For Gun Control  Sit-In");
  d.push("Sarandon Prefers Trump   s Wall to Clinton   s    Moral Judgment   ");
  d.push("Golfer Henrik Stenson pokes a crocodile on Rio Olympic Golf Course");
  d.push("Bosses are already tracking employees with microchip  implants");
  d.push("Donald Trump surely has something else in mind. Will that something else be a new     venture? As the candidate himself might phrase it");
  d.push("which makes what   s happening in Kentucky so interesting. Kentucky Attorney General Andy Beshear (D) has filed a lawsuit to stop Gov. Matt Bevin (R) from slashing the budgets of the state   s public colleges and universities. Beshear says the governor violated state laws governing budget reductions when he imposed a $41 million");
  d.push("Deadly storms hit several states");
  d.push("Why One Woman Pretended to Be a High-School Cheerleader");
  d.push("Trump Cracks Down on Sanctuary Cities");
  d.push("one of the largest US television station operators");
  d.push("Shooter of Truck Terrorist: Soldiers Hesitated to Act Due to Elor Azaria Conviction");
  d.push("Iran challenges need to ship out excess material under nuclear deal");

  d.push("S. D. (AP)        A former police chief in South Dakota charged with killing his pregnant fiancee in a shooting that long appeared to be a hunting accident helped take out more than $750");
  d.push("Chloe Sevigny scores $2.7M for Brooklyn  apartment");
  d.push("What Corvette creator Harley Earl and Steve Jobs shared");
  d.push("Iraqi forces push deeper into western Mosul as civilians flee");
  d.push("Ex-Christie allies sentenced to prison for Bridgegate scandal");
  d.push("This Steve Jobs quote perfectly sums up the difference between billionaires and the rest of us");
  d.push("legislation that has decreased the quality of health care in the U. S. and even caused many individuals and families to lose health insurance altogether. At today   s rally");
  d.push("as the course   s website puts it");
  d.push("Oyster Archaeology: Ancient Trash Holds Clues To Sustainable Harvesting");
  d.push("Syria   s Horrors Visit Turkey Again as Bomber Attacks Kurdish Wedding - The New York Times");
  d.push("last night Bernie Sanders launched a pretty blistering attack on Hillary Clinton");
  d.push("Oil falls on output concern; U.S. stocks down");
  d.push("Recovered WWI German u-boat revives    sea monster    tales");
  d.push("Duke can exhale after battle of SAT scores got  dramatic");
  d.push("Here   s What We Don   t Know About Concussion And  Sport");
  d.push("Trump   s choice for one of his top advisers has been met with a storm of criticism");
  d.push("Mizzou Records Show Students Feared Violence and Felt Targeted by Protesters");
  d.push("Hard-line anti-illegal immigration advocates hired at 2 federal agencies");
  d.push("Suspected Islamic State suicide bomber kills two police in southeast Turkey: sources");
  d.push("5 Fact Checks From Trump   s Cincinnati    Thank-You Tour    Kickoff");
  d.push("Fact-Check -- Top 20 Lies in Hillary   s    Alt-Right    Speech");
  d.push("FBI clears Clinton in email review two days before election");
  d.push("Why Jared Kushner is Donald Trump   s truest heir and most trusted adviser");
  d.push("   We   re going to crush them   : NYPD to broadcast destruction of illegal dirt  bikes");
  d.push("Current version of Peyton Manning among worst-ever Super Bowl starting QBs");
  d.push("Ex-drug CEO Shkreli asks U.S.court to consider blocking subpoena");
  d.push("UK   s Sainsbury   s set to win Home Retail as Steinhoff pulls out");
  d.push("West Ham 0-5 Manchester City: FA Cup third round     as it happened");
  d.push("Why Some Cities and States Are Footing the Bill for Community College");
  d.push("a study suggests. Researchers say having fewer calories in your diet as an adult can lead to a longer and healthier life. But cutting the amount of food at a younger age is not beneficial. Experts analyzed data from two separate studies involving almost 200 rhesus monkeys. And they say the results should also apply to humans. They found adult monkeys who received 30 percent less food tended to live up to two years longer for males and almost six years longer in females. If similar results could be seen proportionally in humans");
  d.push("Nobel Laureate Bob Dylan Is A Literary    Alchemist   ");
  d.push("Pentagon upgrades assessment of ability to defend against ICBMs");
  d.push("What the holidays are like for a recovering alcoholic like me");
  d.push("calling the president   s policies a    manifest disaster    and saying the U. S.    needs a    who will lead.    Cruz has particularly stepped up his criticism of Obama   s plans to allows refugees from   Syria into the U. S. after Tuesday   s fatal attacks on a Brussels airport and subway station that killed 31 and wounded 270 others.  He   s also argued that U. S. law enforcement should have more authority to    patrol and secure    Muslim neighborhoods before their residents become radicalized.    Enough is enough");
  d.push("John Mayer Has More to Say: The Outtakes - The New York Times");
  d.push("U.S. Congress may seek one-week funding extension to avert shutdown");
  d.push("legal experts told TPM. It is the second case this year taking aim at President Donald Trump   s conflicts of interest. The first was a complaint filed by liberal watchdog group Citizens for Responsibility and Ethics accusing Trump of violating the Emoluments Clause");
  d.push("A bridge between two small Indonesian islands collapsed on Sunday");
  d.push("BILL BONNER: It may be 2042 before we recover the losses from the coming stock market crash");
  d.push("you   d think some people wish to live securely");
  d.push("House Clinton and the Wages of Corruption");
  d.push("of Tree and Leaf Farm in Unionville");
  d.push("EXCLUSIVE - Gennifer Flowers Slams    Enabler    Hillary: She    Allowed Him to Do What He Did to Women   ");
  d.push("and as he returned the ball to the infield");
  d.push("several vets complained in interviews with The Post.    I joined the Marine Corps as a direct result of   so to be wined and dined by the very people I joined to fight against");
  d.push("NBC pulls Trump-like episode of    Law &amp Order: SVU   ");
  d.push("Veteran journalist Ted Koppel to Fox   s Sean Hannity: You are    bad for America   ");
  d.push("White House hints at    greater enforcement    of federal marijuana ban in states where it   s legal");
  d.push("Americans    standout answer in a recent poll was    idiot.        Incompetent    and    liar    followed");
  d.push("Biden says he and Obama were tipped off about Trump  dossier");
  d.push("South Korea Restarts Loudspeaker Broadcasts Into North After Nuclear  Test");
  d.push("   The Voice    Contestant Christina Grimmie Killed in Murder-Suicide");
  d.push("LAPD officer Henry Solis sought in killing after fight");
  d.push("Bitterness Overwhelms As Trump And Clinton Campaign Staffers Face Off At Harvard");
  d.push("A Dying Man   s Wish To Donate His Organs Gets Complicated");
  d.push("too");
  d.push("This week   s hottest fashion  sales");
  d.push("MLB trade deadline: Mets get RBI leader Bruce as Lucroy heads to Rangers");

  d.push("Research: Loneliness increases risk of death");
  d.push("the first transgender man to be on the cover of the German edition of Men   s Health");
  d.push("Texas Hat Company Designs Custom Cowboy Hat for Trump");
  d.push("Houses of Worship Poised to Serve as Trump-Era Immigrant Sanctuaries - The New York Times");
  d.push("North Carolina governor says he wants bathroom law partially changed after backlash");
  d.push("   You don   t get to tell us what to do   : Fox News anchor confronts Reince Priebus over Trump   s media criticism");
  d.push("This Trump cabinet show was as dull as it was  pointless");
  d.push("20 States Accuse Generic Drug Companies of Price Fixing - The New York Times");
  d.push("Uber CEO must face price-fixing lawsuit by passengers: U.S. judge");
  d.push("Neera Tanden    who replaced the target of the email hack");
  d.push("Bill Clinton Says Foundation Will See Changes If Hillary Clinton   s  Elected");
  d.push("Three Arrested for Starting Massive Fire on Atlanta Interstate Bridge");
  d.push("who has had a standoffish relationship with the traveling press corps that follows her");
  d.push("   Hamilton    star   s secret cancer  struggle");
  d.push("the report this week that Donald Trump wanted John Kasich to be the real president would have made more of a splash. According to Kasich aides");
  d.push("Rafsanjani   s Impact");
  d.push("breaking sharply with President Trump   s decision to exit the historic Paris climate accord. In a pointed rebuttal to Trump   s announcement in the rose garden of the White House");
  d.push("Golden Globes 2016: the complete list of winners");
  d.push("Study Of Breast Cancer Treatment Reveals Paradox Of Precision Medicine");
  d.push("a controversial professor and neurosurgeon");
  d.push("BREMMER: I   ve never seen a nominee as fundamentally dangerous as Trump");
  d.push("Nordstrom handed a presidential gift certificate");
  d.push("Actor: Hollywood    Afraid    to Fund Certain Films Under Trump");
  d.push("Never Trumpniks Pave Hillary   s Path to Power");
  d.push("U.S. Supreme Court ruling threatens massive talc litigation against J&J");
  d.push("Historic Louisiana floods displace thousands");
  d.push("Pence on email use:    No comparison    to Clinton");
  d.push("Donald Trump has taken his whacks at Ted Cruz");
  d.push("Cruz Campaign Tactics Can   t Be TrusTED");
  d.push("Hackers stole celebrities    before-and-after plastic surgery  pictures");
  d.push("CENTCOM Altered Intel to Make Obama   s Islamic State War Look Better");
  d.push("doctors were certain she was suffering from a large tumor        she was only five years old");
  d.push("Steve Kerr was so mad at the Warriors in Game 1 he destroyed a clipboard during a timeout");
  d.push("Here   s exactly what will happen when the Queen  dies");
  d.push("The Trump/Russia Story Just Got A Lot Darker");
  d.push("Obama   s year-end message: I did it right");
  d.push("    the POTUS said.        The award was a surprise. When Biden realized he was being given the honor");
  d.push("Cuomo   s budget deal in peril over teen felony  law");
  d.push("Female suspect sought in Paris hostage-taking");
  d.push("Trump   s First 100 Days Promise On Climate Change Will Take Longer Than He  Wants");

  d.push("Trump dismisses Russia controversy as    scam    by hostile media");
  d.push("FBI   s Comey meets with top U.S. congressional leaders");
  d.push("Lead contamination in LA housing project said to put 300 kids at risk");
  d.push("The internet roasted David West and Tristan Thompson after they got a little too close during an altercation in Game 5");
  d.push("Jimmy Buffett announces retirement community  venture");
  d.push("Sen. Rubio leads U. S. Rep. Patrick Murphy 47        40 percent and tops U. S. Rep. Alan Grayson 48        40 percent. Murphy and Grayson are ahead of several largely unknown Republican contenders. . . .     With Republican national leaders worried about keeping control of the U. S. Senate");
  d.push("    the cover story of the February 20");
  d.push("Trump   s Carrier deal worthy of    banana    republic: Mexico official");
  d.push("Colombia        As Donald Trump was making his political pilgrimage to the Mexican border");
  d.push("How NHL excused nasty hit that knocked out 3 Ranger  teeth");
  d.push("Candidates make final push before NY  primary");

  d.push("The Real Scandal of Hillary Clinton   s Emails");
  d.push("Flint Residents Win Battle Over Losing Their Homes Because Of Unpaid Water  Bills");
  d.push("I will do the same as you do");
  d.push("Parents caught in disturbing tug-of-war fight with  baby");
  d.push("Father of Benghazi Hero Tyrone Woods: I Endorse Trump");
  d.push("Ryan Lochte survives another week on    Dancing With the  Stars   ");
  d.push("U.S.-backed forces win control of most of Syria   s Manbij from Islamic State: spokesman");
  d.push("Davos makes glacial progress in hike towards gender balance");
  d.push("KKR   s bankrupt former fracking outfit attracts  bidders");
  d.push("Kaine says Trump    loves dictators    at vice presidential debate");
  d.push("The Good Fight review     sleek Good Wife spin-off offers Alicia-free fun");
  d.push("WaPo: Senate Intel Committee Asks For Trump Campaign Documents");
  d.push("You   ll get a kick out of these self-lacing  sneakers");
  d.push("Libya   s Deep State Is Back And Wants The World To Know  It");
  d.push("    Charles Pierce wrote for Esquire");
  d.push("said Sunday that top White House advisor Kellyanne Conway   s comments pushing products from Ivanka Trump   s clothing line on television were    a textbook case of a violation of the law.       This was a textbook case of a violation of the law");
  d.push("Traces of explosives found on human remains from EgyptAir flight crash");
  d.push("authorities said Monday. One of the four sites is a Bronx lot where the Mafia used to hold its induction ceremonies up until a few years");
  d.push("defying a rare criticism from key ally the United States");
  d.push("A Muslim woman was set on fire in New York. Now just going out requires courage");
  d.push("   East Bay Times    Wins Pulitzer For Reporting On Ghost Ship Fire");
  d.push("Homeland season 6 simply can   t compete with reality   s plot twists");
  d.push("Canadian province makes it illegal to require women to wear high heels");
  d.push("Carli Lloyd:    I   ll do anything to win the FA Cup final for Manchester City   ");
  d.push("Clinton   s Dishonesty Cost Her the Midwest   and the Election");
  d.push("Captivity Makes Monkey Microbiomes More Human-Like");
  d.push("Sicko wanted for hurling semen at women in  supermarkets");
  d.push("Teen convicted of homicide in school bathroom  brawl");
  d.push("United made a major change to ensure the nightmare of Flight 3411 doesn   t happen again");
  d.push("but it seems Trump hasn   t bothered to consult his own faith advisers in the current imbroglio. Pastor James MacDonald");
  d.push("Police Say They Have Foiled A Terror Plot In London After A Woman Was Shot By  Officers");
  d.push("N.C.A.A. Ends Boycott of North Carolina After So-Called Bathroom Bill Is Repealed - The New York Times");
  d.push("Oklahoma   s Baker Mayfield charged with public drunkenness and resisting arrest");
  d.push("Airbnb horror story is cautionary tale for  tourists");
  d.push("How I Learned to Tolerate Blake Lively - The New York Times");
  d.push("Proposed NCAA settlement could restore Penn State wins");
  d.push("Trump Admin. Asks Federal Judge To Clarify Order Blocking Travel Ban");
  d.push("North Korea threatens nuclear strike amid US-South Korea drill");
  d.push("Democrats think Trump won on economic issues     but exit polls offer a more complicated story");
  d.push("We visited J. Crew and witnessed why business is a disaster");
  d.push("Handouts to the Agriculture Industry Are Out of Control");
  d.push("Ryan said on the call he won   t campaign with Trump. According to sources");
  d.push("The great unexplained Watergate mystery");
  d.push("How the Clintons Got Rich Selling Influence While Decrying Greed");
  d.push("and on this live blog. Obama downplays ISIS threat in State of the Union speech  State of the Union Live Coverage");
  d.push("   Indie country    takes on the mainstream with true tales from red-state America");
  d.push("Orange Is the New Black:    Friends in Low Places   ");
  d.push("Early vote tally foretells soaring turnout in most expensive House race ever");
  d.push("FBI closes books on legendary D.B. Cooper skyjacking of 1971");
  d.push("Internet captivated by little cubes of raw food");
  d.push("These Syrians Were Finally Fleeing Their Besieged Towns But Then They Were  Attacked");
  d.push("Immigrants Head to Washington to Rally While Obama Is Still There - The New York Times");
  d.push("Hundreds Protest After Minnesota Officer Found Not Guilty In Philando Castile Death");
  d.push("Virginia        In the Pentagon briefing room");
  d.push("Trump Ain   t Gonna Change");
  d.push("CARL ICAHN: Bill Ackman is a liar");
  d.push("state House Speaker Beth Harwell (R) told interns not attend legislature receptions or events and not to give their cell phone numbers to members of the legislature. Durham on Sunday resigned from his position as majority whip");
  d.push("Katy Perry Produces Anti-Trump PSA: Is WWII    History Repeating Itself?   ");
  d.push("Yemen        Signaling a major shift in Yemen   s grinding civil war");
  d.push("Russia returns Israeli tank seized in Lebanon  War");
  d.push("3 charts that show money can   t stop Donald Trump");

  d.push("her department twice received a    prestigious    award for its   practices    an honor that");
  d.push("Former Christie Campaign Aide Calls His Trump Endorsement    Political Opportunism   ");
  d.push("Boy Scout dies after collapsing on troop hiking  trip");
  d.push("California");
  d.push("WhatsApp judge wins little love in Brazil; but respect in his hometown");
  d.push("300 years ago has been discovered in Mexico. The incredible building was once the home and business center for the ruler of an ancient empire which   the Aztecs");
  d.push("My 6-year-old son was brutally killed protecting me from a  rapist");
  d.push("Because I Was Harmed");
  d.push("Clinton selects Kaine as her running mate");
  d.push("CNN Manages to Blow the House Ethics Story");
  d.push("Report: JEB! Bush Takes Pass on Buying Marlins");
  d.push("driven by an Internet frenzy over a tabloid report alleging Cruz had extramarital affairs. Cruz addressed the salacious report in the National Enquirer at an event in Oshkosh");
  d.push("How the LSAT Destroys Socioeconomic Diversity");
  d.push("This pastrami taco is the mashup of your  dreams");
  d.push("if only because they cannot wait to get on with the Trump vs. Hillary Clinton brawl. The unlikability of Sen. Ted Cruz ( .) general fatigue with the GOP race and creeping fatalism in some GOP quarters        not to mention Trump crowning himself the    presumptive nominee           serve to reinforce the media story line. But what if");
  d.push("described how a strange man approached her in a Des Moines hotel Monday night");
  d.push("accusing the billionaire businessman of throwing a    Trumpertantrum    and questioning whether he has the    temperament    to lead.   Speaking to reporters in New Hampshire");
  d.push("Chris Bodenner");
  d.push("One Dead After Car Bomb Explodes In Berlin");
  d.push("FBI stats back up Trump   s warning on  crime");
  d.push("The Sweeping Effects of Trump   s Deal With Carrier");
  d.push("sparked by shifting consumer habits and expected relaxed antitrust enforcement by a Trump White House");
  d.push("my daughter picks out bedtime stories from the picture books on her shelf. And every night");
  d.push("a Mexico   s attorney general said Wednesday.    As of today");
  d.push("Track of the Day:    You   re So Vain   ");
  d.push("Hackers infected DC   s camera network pre-inauguration");
  d.push("U.S. Capitol shooting called suicide lockdown lifted");
  d.push("The Problem With Teaching Preschool Teachers");
  d.push("   Whiskey Tango Foxtrot    with Tina Fey is surprisingly sharp and  funny");
  d.push("Here   s Why There Won   t Be An Independent Investigation Into Russia Anytime  Soon");
  d.push("Anti-Semitism on U.S. College Campuses Skyrockets");
  d.push("Kim Jong Un   s half-brother killed by female assassins with  poison");
  d.push("Hoping the Linsanity can  return");
  d.push("The problem with    don   t eat alone with women   : good character is better than strict rules");
  d.push("Family of Murdered Woman Sues San Francisco over    Sanctuary City   ");
  d.push("a black man legally carrying a concealed weapon");
  d.push("and the opposition to Betsy DeVos");
  d.push("Cuomo   s latest blow to city  taxpayers");
  d.push("000 nuclear weapons in the world");
  d.push("A defaced mural in Maine shows Governor Paul LePage in KKK hood and wearing Mickey Mouse ears");
  d.push("Sanders scores upset victory in Indiana Democratic primary");
  d.push("which are appropriate for the context");
  d.push("Hillary Clinton blames one Comey letter for stopping momentum and the other for turning out Trump voters");
  d.push("Plateau But No Decline: Child Obesity Rates Hold Steady");
  d.push("Bob Dylan Sends Warm Words but Skips Nobel Prize Ceremonies - The New York Times");
  d.push("Google faces first EU fine in 2016 with no deal on cards: sources");
  d.push("Countries where Trump does business are not hit by new travel restrictions");
  d.push("No Charges but Plenty of Blame for Hillary");
  d.push("Aya Cash: The First Time I Ate a Vegetable (I Was 22) - The New York Times");
  d.push("Here   s what we learned from Clinton and Sanders    at Fox News    town hall event");
  d.push("my friends and I would support our more improbable factual claims by following them with the words    ask anyone.     One of us would make a preposterous statement");
  d.push("and reportedly told senators in a subsequent closed session that Sessions may have met with the Russian ambassador to the U. S. on a third occasion that the attorney general had not disclosed. The former FBI director also described Sessions    reaction when Trump sought to speak with Comey alone after a Feb. 14 meeting in the Oval Office");
  d.push("and the fact that she   s the daughter of an immigrant.        John Lithgow shouted out Meryl Streep.        Dolly Parton honored her 9 To 5 costar Lily Tomlin with a Life Achievement award.        And Lily discovered that the award she   d been given was  .        Sarah Paulson shared a moment of camaraderie with her The People v. O. J. Simpson   Courtney B. Vance.        Mahershala Ali spoke about becoming a muslim and telling his mother");
  d.push("Lesson Learned For Baltimore   s Health Commissioner:    I Like A Fight   ");
  d.push("Pakistan PM hits out at    slandering    of his family over wealth");
  d.push("and callous all in the name of attracting as many eyeballs as possible. It went        and still goes        by the motto    Today   s gossip is tomorrow   s news.     It reminded me of a sarcastic   I got from my dad");
  d.push("The Atlantic Daily: Loose Ends and Legacy");
  d.push("saying state election officials don   t have enough time to prepare for it");
  d.push("Hollywood    Power Women    Keep Wallets Closed for Hillary");
  d.push("EPA braces for possible    devastating    25% budget cut");
  d.push("This Boeing private jet is a flying luxury home");
  d.push("Washington boy suffers brain bleed after attempting    Duct Tape Challenge   ");
  d.push("Blood Banks See Massive Response After Orlando Attack");
  d.push("Twitter not reliable predictor of election outcomes: study");
  d.push("a top executive at Sinclair beamed a short commentary piece to many of the company   s 173 stations. In the segment");
  d.push("U. S. society is slipping into a quagmire of Russian disinformation in which the Putin regime will find it very easy to create reality and destroy facts. This has implications not only for U. S. security but also for the country   s psychological health. The recently released report that asserts that Russian president Vladimir Putin has been    cultivating assisting and supporting Trump    for years and that the Russians have compromising information (kompromat) on him is");
  d.push("Philippines attack: dozens feared dead after Manila gunman sets fire to resort");
  d.push("preyed on by foreigners and awash in citizens violated by feral criminals and    illegals.     Through last year   s campaign and into this year");
  d.push("Indonesia turns to manufacturing to counter commodities slump");
  d.push("   No. No. Next question   : Trump flatly denies he ever asked Comey to end probe into Flynn");
  d.push("a Syrian city that has been devastated by constant bombardment. A man carried the boy away from the rubble after a suspected Russian or Syrian regime airstrike in the neighborhood of   Qaterji. He placed him in an orange seat");
  d.push("Donald Trump   s experts are basing his trade policy on a remarkably silly mistake");
  d.push("Adele review: global star shines all the brighter on emotional night");
  d.push("Iowa        Hillary Clinton criticized FBI Director James Comey on Friday for failing to disclose additional information about the nature of a new inquiry into her private email server.    We are 11 days out from perhaps the most important national election of our lifetimes");
  d.push("Pictures: Crucifixion of Jesus Recreated In Annual Central London    Passion Play    Tradition");
  d.push("    Clinton campaign manager Robbie Mook said on    ABC   s    This Week.     Mook   s appearances on ABC and CBS       Face the Nation");
  d.push("Clinton Marks Historic Win As Sanders Vows To Fight On");
  d.push("Robin Hood   s Sherwood Forest faces fracking threat");
  d.push("S. C.        Nikki Haley made her decision over dinner. Three dinners");
  d.push("Time: Inside the British Town Where 1 in 3 Are EU Migrants");
  d.push("U. S. federal forecasters say. After a wild winter in the USA        with blizzards in New Mexico");
  d.push("Al Jazeera employees go out with boozy farewell  bash");
  d.push("the Mormon Tabernacle Choir");
  d.push("Kochs dismiss bombshell Mark Cuban allegation about trying to bribe Donald Trump out of the race");
  d.push("Donald Trump is within striking distance in the Upper Midwest");
  d.push("The week in patriarchy: essentially unconscious from anger");
  d.push("   Guilty But Mentally Ill    Doesn   t Protect Against Harsh Sentences");
  d.push();
  d.push("former Fox News analyst Monica Crowley has taken up a new pursuit: lobbying on behalf of a Ukrainian oligarch who   s advocated for better relations with Russia.  In Foreign Agents Registration Act (FARA) registration documents filed Friday and flagged by   research organization LegiStorm");
  d.push("Exchange Podcast: Giuseppe Sala");
  d.push("Trump Aide Threatens To Primary Freedom Caucus Member");
  d.push("A First In Gaza: A Female Treats Injured Male Soccer Players");
  d.push("The Atlantic Daily: Planetary Politics");
  d.push("Can   t Pay Your Student Loans? The Government May Come After Your House");
  d.push("Jury Awards $55M To Erin Andrews In Lawsuit Over Nude Video Leaked Online");
  d.push("I had to destroy my dad to save my  children");
  d.push("The Wisdom of Mencken and Nock Seems Fresh Today");
  d.push("Donald Trump   s Team Shows Few Signs of Post-Election Moderation - The New York Times");
  d.push("Bernie Sanders    humiliated    Democrats can   t talk to    white working class    voters");
  d.push("The Chicago Meltdown");
  d.push("Exclusive: CBS weighs share options for post-Redstone era - sources");
  d.push("Vice President");
  d.push("Florida Gov. Removes State Attorney From Death Penalty Case");
  d.push("nearly 50 percent of Americans vow to change their behavior come Jan. 1");
  d.push("Impeachment seemed impossible a few days ago. Not anymore");
  d.push("Feds spend $$ studying if college kids eat junk food when they drink");
  d.push("Aus Open: Nadal beats Zverev in epic");
  d.push("leaving intact an 8th U. S. Circuit Court of Appeals decision that threw out the   verdict St. Paul jurors awarded Ventura in 2014. The    former          he was known as Jesse    The Body    ventura in his WW   F days _ and actor turn politician maintains that the best selling book lies about a barroom fight");
  d.push("Chrome is about to get a whole hell of a lot  faster");
  d.push("The Atlantic Policy & Politics Daily: Wanted: Speakers for the July Republican Convention");
  d.push("Pakistan heat wave claims hundreds of lives");
  d.push("Dementia Rates Seem To Have Decreased In The Last Two  Decades");
  d.push("Internet access has never been more ubiquitous        or more underwhelming. Don   t take my word for it. Just ask Wendy Lewis");
  d.push("We need to talk about American values");
  d.push("they   ll have to play hardball. So Tuesday");
  d.push("Understanding the Trump Voter - The New York Times");
  d.push("White House statement on acting attorney general");
  d.push("calling them the    textbook definition of a racist comment.     The speaker condemned the comments as a growing chorus of GOP figures did the same");
  d.push("Sacrificing One Species to Change the Color of Another");
  d.push("those of us in the #NeverTrump movement have come under heavy fire. Using the prospect of a Hillary Clinton presidency as a threat");
  d.push("Goldman CEO takes lead on Wall Street in slamming Trump travel ban");
  d.push("Tony Romo is the insurance policy the Cowboys  needed");
  d.push("Trump feels    totally vindicated    by Comey   s planned  testimony");
  d.push("Time Inc. offloads This Old  House");
  d.push("New Orleans begins removing monument to Confederate Gen. Robert E. Lee");
  d.push("who painfully discover that distancing themselves from President Donald Trump is no easy task.    In SNL Stories    Boycott");
  d.push("    Lavallo said of his planned summer sojourn. If all goes according to plan");
  d.push("and a sickening snap echoed throughout the arena. A split second later");
  d.push("   Underhound Railroad    smuggles dogs from shelters to the  northeast");
  d.push("Donald Trump Tombstone Debuts at Brooklyn Art Gallery");
  d.push("The Missing Piece of the Oscars         Diversity Conversation");
  d.push("How Rangers can make their weakest spot a moot  issue");
  d.push("Why Georgia is turning purple");
  d.push("Report: Rihanna Cancelled Grammys Spot Following    Hysterical       Meltdown   ");
  d.push("Hornacek vaguely rips effort as Knicks    moment of truth is  here");
  d.push("a Twitch streamer and World of Tanks enthusiast stepped away from the livestream at around 4:30 p. m.  . An hour later");
  d.push("Chicago torture video: No bail for 4 suspects");
  d.push("Debate bets being placed range from ratings to Trump   s tie  color");
  d.push("This election has been so important. Support our efforts to cover it");
  d.push("Trump Taj Mahal closing after multiple bankruptcies and union strike");
  d.push("Donald Trump and Bikers Share Affection at Rolling Thunder Rally - The New York Times");
  d.push("Light for the climate: how car colour cuts pollution");
  d.push("Tour the stunning home of the family that built  Miami");
  d.push("N. C.        As he took the stage here in this mountain town Friday afternoon");
  d.push("Iran holding 10 American  sailors");
  d.push("This Is How People Around The World Feel About Traveling To The US  Now");
  d.push("children across America will be staring at the sky in hopes of catching a glimpse of Rudolph or one of his reindeer friends. But for the people snuggled in Russia   s remote Arctic regions there are usually so many reindeer        an estimated 730");
  d.push("Maury Povich talks    daddy    issues");
  d.push("The Best of Vin Scully: Five of the Baseball Hall of Fame Announcer   s Greatest Calls");
  d.push("De Blasio employee arrested for child  pornography");
  d.push("Teenagers on loneliness:    We want to talk to our parents. We need their guidance   ");
  d.push("using Skittles to make an argument about Syrian refugees: This image says it all. Let   s end the politically correct agenda that doesn   t put America first. #trump2016 pic. twitter.  As an analogy");
  d.push("Who is Billy Bush: the man egging on Trump in tape about groping women");
  d.push("Coordinated Bombs in Kabul Kill Senior Afghan Officials at Defense Ministry - The New York Times");
  d.push("Anti-abortion student group sues professor");
  d.push("From Whitewater to Benghazi: A Clinton-Scandal Primer");
  d.push("Singapore blogger seeking U.S. asylum regrets posts in home country");
  d.push("President Trump   s lawyers on revised travel ban repeatedly asked about campaign promises");
  d.push("and his presidency offers   evidence of strains within the party that aren   t going away anytime soon. Anyone looking for   evidence could see it in the results of last week   s Republican gubernatorial primary in Virginia. Many analysts believed Ed Gillespie");
  d.push("close to 30% of the precincts have reported on the Democratic side and the margin");
  d.push("according to major new research that reveals the spread of fringe political views into the mainstream. BuzzFeed News has been given exclusive access to new data from YouGov");
  d.push("Appeals Court Hears Challenge To Obama Power-Plant Emissions Rule");
  d.push("TJ Maxx should terrify Macy   s");  d.push("South Korean prosecutors arrest woman at center of political crisis");
  d.push("Obama To Meet With Hill Dems Wednesday To Discuss Saving O   Care");
  d.push("Britain   s health service in a    humanitarian crisis   : Red Cross");
  d.push("Mysterious gunk is growing on the Jefferson  Memorial");
  d.push("What it   s like to be 13 and have your mom detained in an immigration raid");
  d.push("Texas Diner Re-Brands as    Trump Caf     ");
  d.push("This new Antarctica study is bad news for climate change doubters");
  d.push("How Yelp Reviews Can Help Improve Patient Care - The New York Times");
  d.push("when college students gather        at 4:20 p. m.        in clouds of smoke on campus quads and when pot shops in legal weed states thank their customers with discounts. This year   s edition provides an occasion for pot activists to reflect on how far their movement has come");
  d.push("Listeners Sold Us On What   s Special To Them ... And They Sure Got Specific");
  d.push("casting this as the government improperly taking sides in free speech disputes. Justice Elena Kagan said that a government program that allowed only positive speech and denied negative speech would be a    fairly classic case of viewpoint discrimination");
  d.push("PA.        To live in Appalachia is to love Appalachia. The deep ravines");
  d.push("No survivors after Texas hot air balloon crashes with 16 on board");
  d.push("Fethullah G  len: alleged coup mastermind     and friendly neighbor");
  d.push("Clinton calls for lower price on allergy drug EpiPen");
  d.push("The    Brexit    Campaign: A Cheat Sheet");
  d.push("Historian John Heiser on Why Soldiers of Gettysburg    Came Back Again and Again   ");
  d.push("What    Safe Space    Looks Like In the Classroom");
  d.push("Donald Trump   s Allies Battle for Favor of G.O.P. Givers He Mocked - The New York Times");
  d.push("Italy PM Renzi tells party to step up referendum campaign");
  d.push("a group of more than 100 leading Republican   and defense experts");
  d.push("Brangelina were the last great Hollywood  couple");
  d.push("the Trump administration will succeed in overturning the   court ruling against its travel ban. The nationwide stay of the ban issued by Judge James Robart");
  d.push("the Air Force vet who buzzed Hillary Clinton at this week   s candidate forum with a tough question on her mishandling of classified information");
  d.push("Inside Fidel Castro   s life of luxury and ladies while country  starved");
  d.push("Burkina Faso   s long night of horror in killing spree by militants");
  d.push("nonpartisan Commission on Presidential Debates serves as the debate sponsor and sets the participation criteria");

  d.push("The chillest places in the United States");
  d.push("Hacked Colin Powell Email: Hillary Clinton    Using Me as A Blanket    to Cover Up Scandal");
  d.push("Trump   s immigration speech was spot-on     but     ");
  d.push("Two dead at Shi   ite processions in northern Nigeria");
  d.push("Trump   s Favorite Big Bank Is Doing Great After His Surprise  Win");
  d.push("by all accounts");
  d.push("What   s behind the ludicrous roster on baseball   s biggest  tank");
  d.push("Ignore the headlines: US consumers are loving life right now");
  d.push("Carmelo jolts Team USA awake to turn worry into  slaughter");
  d.push("Dem Goo-Goo Wisconsin Debate Blogging #5");
  d.push("same JaVale McGee. The Golden State Warriors backup center compared TNT analyst Shaquille O   Neal to a minstrel        and to Bert Williams        after the NBA legend made fun of the journeyman   s haircut in an ongoing troll war. The feud started after McGee made frequent appearances on TNT   s    Inside the NBA");
  d.push("Artist Peter Doig victorious as court agrees    $10m    painting is not his work");
  d.push("The FBI is hunting for a man who poured suspicious liquid on Whole Foods    buffets");
  d.push("and their search has taken them to an Arizona boneyard where the Corps    old   Hornets have been gathering dust for years. The jets are being reclaimed and refurbished by Boeing after the service branch was caught short on planes because of long delays in the rollout of the    .    We are very focused on our current readiness");
  d.push("ask yourself: Would you pass the Iverson test? 	I don   t think I would. 	The financial difficulties later in life subjected Iverson to a great deal of ridicule: You can get busted for weed and an illegal gun and it   s no big deal        not in Philly!        but if your money isn   t right");
  d.push("on air");
  d.push("Pat Toomey   s Chances");
  d.push("returned to his wife and newborn child");
  d.push("Aubrey Plaza:    Things take on a different meaning when death comes so close   ");
  d.push("teaching fellow");
  d.push("How Trump can get his groove back");
  d.push("We Asked Young People To Explain Why They   re Voting For Marine Le  Pen");
  d.push("   Why wait?   : Ted Cruz asks why NBC didn   t release damning tapes of Donald Trump during GOP primaries");
  d.push("Rookie Doctors Will Soon Be Allowed To Work Up To 28 Hours Straight");
  d.push("Rebuilding the GOP after November 9");
  d.push("RG3   s injury would be jarring if it weren   t so sadly  inevitable");
  d.push("although already extensive");
  d.push("Kaine named Russian President Vladimir Putin");
  d.push("Scalise remains in critical condition after shooting");
  d.push("a   Republican congressman from Kansas");
  d.push("including two Americans");
  d.push("   I don   t want you to get shooted   : daughter of slain Minnesota man   s girlfriend");
  d.push("Hollywood Analyst Warns Studios    Big-Budget Bombs    Coming in 2017");
  d.push("These are the 12 most popular private jet destinations every year");
  d.push("Lawmakers express shock and concern about Trump disclosure of classified information");
  d.push("Do Everything Yourself: The Lessons Of Punk Renaissance Woman Vivien Goldman");
  d.push("a Republican");
  d.push("McConnell Thinks Hundreds Protesting His Event Are Just Upset About Election");
  d.push("it is worth noting something that is being ignored: In practice");
  d.push("See historic photos from legendary and iconic photographer Paul Strand");
  d.push("The East Coast Digs Out");
  d.push("The Cost of Keeping Lenin Looking Like Lenin");
  d.push("Teachers to Wear Black Lives Matter Shirts to Class to Protest    Systemic Oppression   ");
  d.push("Maria Sharapova   s return to tennis would sit more easily if she showed contrition");
  d.push("irking NYPD brass.    The governor was there almost instantaneously. It was outrageous");
  d.push("users are entitled to a replacement or a refund of their phones");
  d.push("Yahoo wants bidders to submit offers to buy the company in the next 2 weeks");
  d.push("The looming split between Trump and Ryan");
  d.push("Can Teenage Defiance Be Manipulated for Good? - The New York Times");
  d.push("Obama treads on Trump   s Twitter turf to reflect on presidential achievements");
  d.push("state courts order license suspensions for 300");
  d.push("Jenna Lyons out at J.Crew after 26  years");
  d.push("   Awkward moment    for Prince Harry in minute   s silence for Fidel Castro");
  d.push("as it was unfolding Sunday night");
  d.push("New Poll: Tie in Georgia   s Sixth Congressional District Special Election Despite $23 Million Raised by Democrat");
  d.push("Another Clinton Email Scandal");
  d.push("Apple Offers Free App to Teach Children Coding (iPads Sold Separately) - The New York Times");
  d.push("Donald Trump Lashes Out At The New York Times Yet Again");
  d.push("Trump on VP search: Looking for candidate with congressional ties");
  d.push("Multi-millionaire bin Laden screwed his family in his  will");
  d.push("American Keith Broomfield killed fighting in Syria");
  d.push("the war planes of Nazi Germany and fascist Italy chose a market day to bomb a Basque town");
  d.push("Joey from Friends becomes first TV character to be    virtually immortalized   ");
  d.push("I Feel Like    I Am Orlando    Though I Live Thousands Of Miles Away");
  d.push("Traitors no more? North Korean defectors    forgiven   ");
  d.push("who had headed the company   s   program since August. Levandowski was the nexus in a   suit filed by Google since the executive once led the   initiatives at both tech companies. Levandowski was sued in March by his former employer        Waymo");
  d.push("Minn.        Two police cruisers had just pulled up to the apartment building");
  d.push("The jewels of Iran   s    sad-eyed    princess");
  d.push("and then there are very big public companies");
  d.push("Nigel Slater   s spiced lentil soup recipe");
  d.push("Hundreds Attend Vigils For MP Jo  Cox");
  d.push("Spotify says growth has quickened since Apple Music   s launch");
  d.push("the House GOP reversed course and withdrew the rules change that would have gutted the Office of Congressional Ethics");

  d.push("Creating a masculine bedroom retreat for a college freshman");
  d.push("the top suspect in last year   s deadly Paris attacks");
  d.push("The Fate of the Undocumented Teachers for America");
  d.push("seeking to compile a list of 15 to 20 potential picks for her team to start vetting by late spring");
  d.push("Search for Malaysia Airlines Flight 370 Is Called Off After Nearly 3 Years - The New York Times");
  d.push("Express: Somali Man Says Streets of His Home Country are Safer Than London");
  d.push("A Politically Charged Night at the SAG Awards");
  d.push("Republican senators have been able to punt on some of the tough decisions in writing their repeal legislation until after they saw what the CBO said about the House Obamacare repeal bill. That CBO report has now landed");
  d.push("New poll finds 9 in 10 Native Americans aren   t offended by Redskins name");
  d.push("U.N. Finally Apologizes For Cholera In Haiti ... But Omits One Point");
  d.push("four Statues of Liberty could be stacked on top of each other and still not reach the surface. And the Hranicka Propast");
  d.push("Canada Receives Record Numbers of Mexican Asylum Seekers After Trudeau   s Welcome Tweet");
  d.push("Dallas school police use handcuffs to restrain 7-year-old boy");
  d.push("   The Myth of a U. S. Military    Readiness    Crisis    (August 9) General David Petraeus and Brookings Institution scholar Michael O   Hanlon sadly perpetuate one of the most deeply held myths about the state of the U. S. military: that its    readiness    problems are a myth. The     Hanlon piece is off the mark in a number of respects. To begin with");
  d.push("How Trump can beat Putin at his media game");
  d.push("but fellow government workers won   t be getting discounts at his Pennsylvania Avenue hotel        even if the hotel   s website promises otherwise. Scroll through the offers on the Trump International Hotel   s website and you   ll see a section advertising special government rates");
  d.push("Senate intel member says Trump closer to impeachment  process");
  d.push("25");
  d.push("Reports Of Medical Breakthroughs Often Don   t Prove Out");
  d.push("Summer Camps Say They   re Not Sweating Over Zika Risk");
  d.push("Lose weight by learning your favorite stars    dance  moves");

  d.push("Prince   Bin Talal Bin Abdulaziz al Saud reminded Trump that he had    bailed out    the presidential frontrunner multiple times in the past. Trump:You base your statements on photoshopped pics? I bailed you out twicea 3rd time");
  d.push("Why Church Hymns Are Best Sung in Bars");
  d.push("Reactions To Trump   s Attack On John Lewis:    Your Ignorance Is Astounding   ");
  d.push("Powerful    Gene Drive    Can Quickly Change An Entire Species");
  d.push("The GOP may be making a big change in how it deals with race relations");
  d.push("Brazil markets plunge as Temer scandal threatens reforms");
  d.push("following years of extreme drought in the region.          Probably close to 6 inches of rain came in the last three months");
  d.push("1963        standing at a podium in front of a crowd of over 200");
 
  d.push("5 health conditions that don   t really  exist");
  d.push("the Financial Choice Act");
  d.push("Trump Aide Threatens To Primary Freedom Caucus Member");
  d.push("Trump says he doesn   t want a    poor person    handling economy");
  d.push("a bomb packed with metal shrapnel exploded in the Manhattan neighborhood of Chelsea");
  d.push("Class project to make slave auction posters outrages  parents");
  d.push("The Comedy Is Finished");
  d.push("we tend to imagine him as the raging");
  d.push("Police: Florida Mom Fatally Shoots Daughter After Mistaking Her For Intruder");
  d.push("ending his long history of stoking unfounded doubts about the nation   s first African American president but also seeking to falsely blame Democratic rival Hillary Clinton for starting the rumors.    Hillary Clinton and her campaign of 2008 started the birther controversy. I finished it. I finished it. You know what I mean");
  d.push("Fact-checking Trump   s claim that he has no business ties to Russia");
  d.push("What we know about U.S. probes of Russian meddling in 2016 election");
  d.push("hours after authorities arrested several members of that group and killed one of the most prominent occupiers. The frenzy of activity at Malheur National Wildlife Refuge in Harney County marked a sudden escalation in the ongoing standoff that has simmered for more than three weeks");
  d.push("The Kids Who Lie About Their Age to Join Facebook");
  d.push("in fact");
  d.push("Hillary Clinton   s Plan For America   s Students");
  d.push("Ernest Hemingway: The man behind the cultivated image of hyper-masculinity");

  d.push("stretching across the second half of the 20th century        when   was");
  d.push("The Mets are the  suckers");
  d.push("   Children of Satan   : CAIR Claims Pro-Trump Hate Mail Hits Mosques");
  d.push("Crown Prince returns to Bangkok as Thailand holds vigil for ailing king");
  d.push("Bees Added To U.S. Endangered Species List For 1st Time");
  d.push("Accused gunman charged in fatal San Diego police shooting");
  d.push("according to a report Monday. The fast food chain will replace the fruity   refresher with Sprite TropicBerry");
  d.push("The Trump Revolution");
  d.push("Shimon Peres   s Health");
  d.push("Second Trump Army Secretary Nominee Withdraws");
  d.push("J.Crew   s sales continue to slide into  2017");
  d.push("there was one other statement this weekend that makes me think I may want to do the same. In a    60 Minutes    interview last night filled with substantive news");
  d.push("Trump   s victory is leading to lunacy in high places");
  d.push("Hidden cameras show airport workers stealing from bags");
  d.push("JAMES CLAPPER: Comey was    uneasy    about having dinner with Trump");
  d.push("This is the    reckoning point    for a bunch of oil producers");
  d.push("in effect");
  d.push("A Car Accident Throws a Productive Life Into Turmoil - The New York Times");
  d.push("Arkansas        Juanita Broaddrick a cr     son compte Twitter en 2009. Cette femme de 73 ans");
  d.push("Experience America at the Time of the Great War");
  d.push("FBI says Orlando gunman had been on watchlist; six wounded in shooting still critically injured");
  d.push("thought to be bringing food and aid to a bus caravan carrying 5");
  d.push("23");
  d.push("protesters hit the streets in big cities around the country");
  d.push("Committee calls for firing of judge who told woman    keep your knees together   ");
  d.push("Tommy Hilfiger is moving to  Midtown");
  d.push("How A Painkiller Designed To Deter Abuse Helped Spark An HIV Outbreak");
  
  return d;
 }
